site_name: OptiGUI documentation
repo_url: https://github.com/opekope2/OptiGUI
copyright: Â© 2022-2024 opekope2
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - Resource packs:
    - Basic information & syntax: syntax.md
    - Replacing GUI textures: format.md
    - Migration guide: migrate.md
    - Conditional loading: conditional.md
  - For developers:
    - Develop OptiGUI: develop.md
    - Using OptiGUI in a mod: usage.md
  - API docs:
    - Latest: kdoc/latest
    #CI_KDOC_PLACEHOLDER
    - 2.3.0-alpha.2: kdoc/2.3.0-alpha.2
    - 2.1.7: kdoc/2.1.7
    - 2.1.6: kdoc/2.1.6
    - 2.2.0-alpha.1: kdoc/2.2.0-alpha.1
    - 2.1.5: kdoc/2.1.5
    - 2.1.4: kdoc/2.1.4
    - 2.1.3: kdoc/2.1.3
    - 2.1.2: kdoc/2.1.2
    - 2.1.1: kdoc/2.1.1
    - 2.1.0: kdoc/2.1.0
    - 2.1.0-beta.3: kdoc/2.1.0-beta.3
    - 2.1.0-beta.2: kdoc/2.0.0-beta.2
    - 2.1.0-beta.1: kdoc/2.1.0-beta.1
    - 2.0.0-beta.3: kdoc/2.0.0-beta.3
    - 2.0.0-beta.2: kdoc/2.0.0-beta.2
    - 2.0.0-beta.1: kdoc/2.0.0-beta.1
  - API docs (Java syntax):
    - Latest: javadoc/latest
    #CI_JAVADOC_PLACEHOLDER
    - 2.3.0-alpha.2: javadoc/2.3.0-alpha.2
    - 2.1.7: javadoc/2.1.7
    - 2.1.6: javadoc/2.1.6
    - 2.2.0-alpha.1: javadoc/2.2.0-alpha.1
    - 2.1.5: javadoc/2.1.5
    - 2.1.4: javadoc/2.1.4
    - 2.1.3: javadoc/2.1.3
    - 2.1.2: javadoc/2.1.2
    - 2.1.1: javadoc/2.1.1
    - 2.1.0: javadoc/2.1.0
    - 2.1.0-beta.3: javadoc/2.1.0-beta.3
    - 2.1.0-beta.2: javadoc/2.0.0-beta.2
    - 2.1.0-beta.1: javadoc/2.1.0-beta.1
    - 2.0.0-beta.3: javadoc/2.0.0-beta.3
    - 2.0.0-beta.2: javadoc/2.0.0-beta.2
    - 2.0.0-beta.1: javadoc/2.0.0-beta.1
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.caret
extra_css:
  - stylesheets/chips.css
use_directory_urls: false
