[versions]
java = "17" # Don't forget to update *.mixins.json
kotlin = "1.9.22"
optigui = "2.3.0-beta.1"
minecraft = "1.20.2"
yarn = "1.20.2+build.4"
fabric-loom = "1.5-SNAPSHOT"
fabric-loader = "0.15.7"
fabric-api = "0.91.6+1.20.2"
fabric-language-kotlin = "1.10.18+kotlin.1.9.22"
commons-text = "1.11.0"
ini4j = "0.5.4"
dokka = "1.9.20"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
apache-commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
ini4j = { group = "org.ini4j", name = "ini4j", version.ref = "ini4j" }
dokka-base = { group = "org.jetbrains.dokka", name = "dokka-base", version.ref = "dokka" }
dokka-plugin-java-syntax = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokka" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
